version: "3.7"

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    environment:
      - TZ=Europe/Warsaw
    ports:
      - "1883:1883"
    volumes:
      - ./config:/mosquitto/config/