version: "3.7"

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    environment:
      - TZ=Europe/Warsaw
    ports:
      - "1883:1883"
    volumes:
      - ./config:/mosquitto/config/
  node-red:
    image: nodered/node-red:latest
    container_name: node-red
    environment:
      - TZ=Europe/Warsaw
    ports:
      - "1880:1880"
    volumes:
      - node-red-data:/data

volumes:
  node-red-data: